#!/bin/sh
#

HOLD_BACKUPS=5
BACKUP_STORE=/mnt/backup-cache/feeble

#######################
#
# don't modify atfer here
#
########################

export CURRENT_BACKUP_DIR=$BACKUP_STORE/`date +%Y-%m-%d`
#BASE_DIR=`pwd dirname $0`
BASE_DIR=/etc/backup-script

#umask 007

mkdir_err=`mkdir $CURRENT_BACKUP_DIR`
if [ $? != 0 ]; then
  echo "Das Verzeichnis $CURRENT_BACKUP_DIR exsistiert bereits."
  echo "Kein Backup angelegt."
  echo "mkdir-Fehlermeldung:"
  echo $mkdir_err
  exit 1
fi

cd $CURRENT_BACKUP_DIR

run-parts $BASE_DIR/tasks

chown -R backup.backup $CURRENT_BACKUP_DIR
chmod -R 660 $CURRENT_BACKUP_DIR
chmod 750 $CURRENT_BACKUP_DIR

#if [ -e $BACKUP_STORE/current ]; then
rm -f $BACKUP_STORE/current
#fi
ln -sf $CURRENT_BACKUP_DIR $BACKUP_STORE/current

# delete old backups
BACKUPS=`ls -d -1 $BACKUP_STORE/????-??-??`
NUM_BACKUPS=`echo "$BACKUPS"|wc -l`
if [ $NUM_BACKUPS -gt $HOLD_BACKUPS ]; then
  NUM_DIRS_TO_DEL=`echo "$NUM_BACKUPS-$HOLD_BACKUPS"|bc`
  DIRS_TO_DEL=`echo "$BACKUPS"|head -n $NUM_DIRS_TO_DEL -`
#  echo $NUM_DIRS_TO_DEL backups zu löschen
  rm -r $DIRS_TO_DEL
fi
