#!/bin/sh

DB_BACKUPFILE=${BACKUPFILE_PREFIX}postgres_dump.sql.bz2
DB_ERRORLOG=${BACKUPFILE_PREFIX}postgres_backup.errlog

touch $DB_BACKUPFILE
touch $DB_ERRORLOG
chown postgres $DB_BACKUPFILE
chown postgres $DB_ERRORLOG
su postgres -c "/usr/bin/pg_dumpall 2>$DB_ERRORLOG | bzip2 >$DB_BACKUPFILE" || exit 1
chown root $DB_BACKUPFILE
if [ -s $DB_ERRORLOG ]; then
  chown root $DB_ERRORLOG
else
  rm $DB_ERRORLOG
fi
