#!/bin/sh

BACKUP_DIRS="/etc /var/lib/afbackup /var/lib/afbackup-client"

for dir in $BACKUP_DIRS ; do
 FILE=`basename $dir`
 tar -cjf $CURRENT_BACKUP_DIR/$FILE.tar.bz2 -C $dir .
done

dpkg --get-selections |gzip >$CURRENT_BACKUP_DIR/dpkg-selecions.gz
