#!/bin/sh

. $CONF_FILE
echo $SYSTEM_DIRS

for dir in $SYSTEM_DIRS ; do
 FILE=`basename $dir`
 tar -cjf $CURRENT_BACKUP_DIR/$FILE.tar.bz2 -C $dir . || exit 1
done
if [ ! -s $CURRENT_BACKUP_DIR/$FILE.tar.bz2 ]; then
    echo $CURRENT_BACKUP_DIR/$FILE.tar.bz2 not correct
    exit 1
fi

dpkg --get-selections |gzip >$CURRENT_BACKUP_DIR/dpkg-selecions.gz || exit 1
if [ ! -s $CURRENT_BACKUP_DIR/dpkg-selecions.gz ]; then
    echo $CURRENT_BACKUP_DIR/dpkg-selecions.gz not correct
    exit 1
fi
