#!/bin/sh

. $CONF_FILE

for dir in $SYSTEM_DIRS ; do
 FILE="${BACKUPFILE_PREFIX}`basename $dir`".tar.bz2
 tar -cjf $FILE -C $dir . || exit 1
 if [ ! -s $FILE ]; then
    echo $FILE not created
    exit 1
 fi
done

DPKG_FILE=${BACKUPFILE_PREFIX}dpkg-selecions.gz
dpkg --get-selections |gzip >$DPKG_FILE || exit 1
if [ ! -s $DPKG_FILE ]; then
    echo $DPKG_FILE not correct
    exit 1
fi
