#!/bin/sh

. $CONF_FILE

for dir in $DIRECTORIES ; do
 FILE=${BACKUPFILE_PREFIX}dir_`basename $dir`
 tar -cjf $FILE.tar.bz2 -C $dir . || exit 1
done

if [ ! -s $FILE.tar.bz2 ]; then
    echo $FILE.tar.bz2 not correct
    exit 1
fi
