#!/bin/sh

. $CONF_FILE

for dir in $DIRECTORIES ; do
 FILE=${BACKUPFILE_PREFIX}dir_`basename $dir`
 tar -cjf $FILE.tar.bz2 --warning=no-file-changed -C $dir .
 RC_TAR=$?
 if [ ${RC_TAR} -gt 1 ]; then
  echo failure during taring files
  exit ${RC_TAR}
 fi
done
